objects = dmat3.o steuerung_maketables.o input4_mod.o gaus3.o input_cont.o cont_unstable_mod.o gaussint.o util.o prop_mod.o potential3_mod.o extract_sigma_prop.o tmat4_mod.o output4_mod.o cpole2.o vertices_mod.o vertices_5h7h_mod.o resauto.o make_tables.o use_minuit_2.o ccmn4.o observables.o data_observables.o 

include make.inc
 
.SUFFIXES: .F90 .f90


VPATH=tools tools/opt tools/poles tools/new_sigma

ccmn4:  $(objects) 
	$(FC) -o ccmn4 $(FFLAGS)  $(objects) $(LIB)


.F90.o          :
	$(F90) $(FFLAGS) -c $<

.f90.o          :
	$(F90) $(FFLAGS) -c $<



.PHONY : clean
clean: 
	rm -f ccmn4 $(objects) *.mod

.PHONY : run
run:
	time ./ccmn4

#--------------------------------------------------------------------------------------------------------------------------------
#
#   Provides clean plots (no results, only data) in plot_minuit and tau_res
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : cleanplot
cleanplot:
#	tar xvf plot_minuit/empty_plots.tar.gz -C plot_minuit/
	tar xvf tau_res/plots_taures_fitB_JuBo2015.tar.gz -C tau_res/
	cp tau_res/plots_taures_fitB_JuBo2015/*.agr tau_res
	tar xvf plot_minuit/plots_fitresult_fitB_JuBo2015.tar.gz -C plot_minuit/
	cp plot_minuit/plots_fitresult_fitB_JuBo2015/*.agr plot_minuit
#	tar xvf tau_res/empty_pin_plots_totally_empty.tar.gz -C tau_res/
	
#--------------------------------------------------------------------------------------------------------------------------------
#
#   Provides clean plots (no results, only data) for phase shift and inelasticity
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : cleandel
cleandel:
	tar xvf del_res/empty_del_plots.tar.gz -C del_res/
#	tar xvf del_res/empty_del_plots_totally_empty.tar.gz -C del_res/
#--------------------------------------------------------------------------------------------------------------------------------

	
#--------------------------------------------------------------------------------------------------------------------------------
#
#   Plots total cross sections for piN --> MB
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plotcs
plotcs:
	xmgrace plot_minuit/total_cs_etan.agr  -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:3 -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 1 -bxy 1:3  &
	xmgrace plot_minuit/total_cs_KzL.agr  -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:4 -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 1 -bxy 1:4  &
	xmgrace plot_minuit/total_cs_KzSz.agr  -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:5  &
	xmgrace plot_minuit/total_cs_KpSm.agr  -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:6  &
	xmgrace plot_minuit/total_cs_KpSp.agr  -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:7  &
#	xmgrace plot_minuit/total_cs_etan_pcs.agr -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:3 -settype xy -autoscale none -block plot_minuit/partial_cs_res/S11.txt  -graph 0 -bxy 1:3 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P11.txt  -graph 0 -bxy 1:3  -settype xy -autoscale none -block plot_minuit/partial_cs_res/P13.txt  -graph 0 -bxy 1:3  -settype xy -autoscale none -block plot_minuit/partial_cs_res/D13.txt  -graph 0 -bxy 1:3 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D15.txt  -graph 0 -bxy 1:3 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F15.txt  -graph 0 -bxy 1:3  -settype xy -autoscale none -block plot_minuit/partial_cs_res/F17.txt  -graph 0 -bxy 1:3 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G17.txt  -graph 0 -bxy 1:3  -settype xy -autoscale none -block plot_minuit/partial_cs_res/G19.txt  -graph 0 -bxy 1:3 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H19.txt  -graph 0 -bxy 1:3&
#		xmgrace plot_minuit/total_cs_KzL_pcs.agr -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:4 -settype xy -autoscale none -block plot_minuit/partial_cs_res/S11.txt  -graph 0 -bxy 1:4 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P11.txt  -graph 0 -bxy 1:4  -settype xy -autoscale none -block plot_minuit/partial_cs_res/P13.txt  -graph 0 -bxy 1:4  -settype xy -autoscale none -block plot_minuit/partial_cs_res/D13.txt  -graph 0 -bxy 1:4 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D15.txt  -graph 0 -bxy 1:4 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F15.txt  -graph 0 -bxy 1:4  -settype xy -autoscale none -block plot_minuit/partial_cs_res/F17.txt  -graph 0 -bxy 1:4 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G17.txt  -graph 0 -bxy 1:4  -settype xy -autoscale none -block plot_minuit/partial_cs_res/G19.txt  -graph 0 -bxy 1:4 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H19.txt  -graph 0 -bxy 1:4&
#		xmgrace plot_minuit/total_cs_KzSz_pcs.agr -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/S11.txt -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P11.txt  -graph 0 -bxy 1:5  -settype xy -autoscale none -block plot_minuit/partial_cs_res/P13.txt  -graph 0 -bxy 1:5  -settype xy -autoscale none -block plot_minuit/partial_cs_res/D13.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D15.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F15.txt  -graph 0 -bxy 1:5  -settype xy -autoscale none -block plot_minuit/partial_cs_res/F17.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G17.txt  -graph 0 -bxy 1:5  -settype xy -autoscale none -block plot_minuit/partial_cs_res/G19.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H19.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/S31.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P31.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P33.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D33.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D35.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F35.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F37.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G37.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G39.txt  -graph 0 -bxy 1:5 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H39.txt  -graph 0 -bxy 1:5&
#		xmgrace plot_minuit/total_cs_KpSm_pcs.agr -settype xy -autoscale none -block plot_minuit/fit_result/total_cs/total_cs.dat  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/S11.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P11.txt  -graph 0 -bxy 1:6  -settype xy -autoscale none -block plot_minuit/partial_cs_res/P13.txt  -graph 0 -bxy 1:6  -settype xy -autoscale none -block plot_minuit/partial_cs_res/D13.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D15.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F15.txt  -graph 0 -bxy 1:6  -settype xy -autoscale none -block plot_minuit/partial_cs_res/F17.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G17.txt  -graph 0 -bxy 1:6  -settype xy -autoscale none -block plot_minuit/partial_cs_res/G19.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H19.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/S31.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P31.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P33.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D33.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D35.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F35.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F37.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G37.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G39.txt  -graph 0 -bxy 1:6 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H39.txt  -graph 0 -bxy 1:6&
#		xmgrace plot_minuit/total_cs_KpSp_pcs.agr -settype xy -autoscale none -block plot_minuit/partial_cs_res/S31.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P31.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/P33.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D33.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/D35.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F35.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/F37.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G37.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/G39.txt  -graph 0 -bxy 1:7 -settype xy -autoscale none -block plot_minuit/partial_cs_res/H39.txt  -graph 0 -bxy 1:7&

#--------------------------------------------------------------------------------------------------------------------------------
#
#   Plots partial waves for piN --> piN
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot1
plot1:
	xmgrace tau_res/s11_p11.agr -autoscale none -block tau_res/S11.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/S11.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/S11.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/S11.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/P11.txt -graph 2 -bxy 1:2 -autoscale none -block tau_bgd/P11.txt -graph 2 -bxy 1:2 -autoscale none -block tau_res/P11.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/P11.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/s31_p31.agr -autoscale none -block tau_res/S31.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/S31.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/S31.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/S31.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/P31.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/P31.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/P31.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/P31.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/p13_d13.agr -autoscale none -block tau_res/P13.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/P13.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/P13.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/P13.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/D13.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/D13.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/D13.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/D13.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/p33_d33.agr -autoscale none -block tau_res/P33.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/P33.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/P33.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/P33.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/D33.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/D33.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/D33.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/D33.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/d15_f15.agr -autoscale none -block tau_res/D15.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/D15.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/D15.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/D15.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/F15.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/F15.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/F15.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/F15.txt -graph 3 -bxy 1:3 -autoscale none  & 	 
	xmgrace tau_res/d35_f35.agr -autoscale none -block tau_res/D35.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/D35.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/D35.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/D35.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/F35.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/F35.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/F35.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/F35.txt -graph 3 -bxy 1:3 -autoscale none  & 	 
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot1high
plot1high:
	xmgrace tau_res/f17_g17.agr -autoscale none -block tau_res/F17.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/F17.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/F17.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/F17.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/G17.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/G17.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/G17.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/G17.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/f37_g37.agr -autoscale none -block tau_res/F37.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/F37.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/F37.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/F37.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/G37.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/G37.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/G37.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/G37.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/g19_h19.agr -autoscale none -block tau_res/G19.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/G19.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/G19.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/G19.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/H19.txt -graph 2  -bxy 1:2 -autoscale none -block tau_bgd/H19.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/H19.txt -graph 3 -bxy 1:3 -autoscale none -block tau_bgd/H19.txt -graph 3 -bxy 1:3 -autoscale none &
	xmgrace tau_res/g39_h39.agr -autoscale none -block tau_res/G39.txt -graph 0 -bxy 1:2 -autoscale none -block tau_bgd/G39.txt -graph 0 -bxy 1:2 -autoscale none -block tau_res/G39.txt -graph 1 -bxy 1:3 -autoscale none -block tau_bgd/G39.txt -graph 1 -bxy 1:3 -autoscale none -block tau_res/H39.txt -graph 2  -bxy 1:2 -autoscale none -block tau_res/H39.txt -graph 3 -bxy 1:3 -autoscale none &
#--------------------------------------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------------------------------------

#
#   Plots Differential cross sections, Polarization for pi^-p --> eta n
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot2
plot2:
	xmgrace plot_minuit/dsdo_etaN_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1489.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1492.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1496.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1498.dat -graph 3 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1499.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1502.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1507.dat -graph 6 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1509.dat -graph 7 -bxy 1:2 -autoscale none &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_etaN_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1512.dat -graph 0 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1516.dat -graph 1 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1522.dat -graph 2 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1526.dat -graph 3 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1530.dat -graph 4 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1534.dat -graph 5 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1545.dat -graph 6 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1576.dat -graph 7 -bxy 1:2 -autoscale none &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_etaN_3.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1587.dat -graph 0 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1608.dat -graph 1 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1635.dat -graph 2 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1648.dat -graph 3 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1664.dat -graph 4 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1674.dat -graph 5 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1690.dat -graph 6 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1729.dat -graph 7 -bxy 1:2 -autoscale none & 	 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_etaN_4.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1739.dat -graph 0 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1792.dat -graph 1 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1805.dat -graph 2 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1832.dat -graph 3 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1872.dat -graph 4 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1897.dat -graph 5 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1904.dat -graph 6 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1948.dat -graph 7 -bxy 1:2 -autoscale none & 	 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_etaN_5.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN1988.dat -graph 0 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN2024.dat -graph 1 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN2070.dat -graph 2 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN2114.dat -graph 3 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN2148.dat -graph 4 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN2235.dat -graph 5 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_differential_cs/dsdo_etaN2412.dat -graph 6 -bxy 1:2 -autoscale none & 	 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_x_dsdo_etaN_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1739.dat -graph 0 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1792.dat -graph 1 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1832.dat -graph 2 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1872.dat -graph 3 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1904.dat -graph 4 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1948.dat -graph 5 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_1988.dat -graph 6 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_2024.dat -graph 7 -bxy 1:2 -autoscale none & 	 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_x_dsdo_etaN_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_2070.dat -graph 0 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_2114.dat -graph 1 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_2148.dat -graph 2 -bxy 1:2 -autoscale none -block	plot_minuit/fit_result/etaN_polarization/Pxdsdo_etaN_2235.dat -graph 3 -bxy 1:2 -autoscale none & 	  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_etaN.agr -settype xy -autoscale none -block plot_minuit/fit_result/etaN_polarization/pola_etaN1765.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_polarization/pola_etaN1819.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_polarization/pola_etaN1860.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_polarization/pola_etaN1901.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_polarization/pola_etaN1933.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/etaN_polarization/pola_etaN1979.dat -graph 5 -bxy 1:2 & 	 
#----------------------------------------------------------------------------------------------------------------------------------------------------------
#
#   Plots Differential cross sections, Polarization and Spinrotation parameter of pi^-p --> K^0 Lambda
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot3
plot3:
	xmgrace plot_minuit/dsdo_K0Lam_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1626.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1633.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1648.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1661.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1670.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1676.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1678.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1681.dat -graph 7 -bxy 1:2  &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0Lam_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1684.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1686.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1687.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1689.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1693.5.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1698.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1701.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1707.dat -graph 7 -bxy 1:2 &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0Lam_3.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1724.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1742.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1758.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1792.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1797.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1819.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1825.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1845.5.dat -graph 7 -bxy 1:2 & 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0Lam_4.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1879.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1909.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1930.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1934.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1938.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1966.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1973.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1978.dat -graph 7 -bxy 1:2 &  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0Lam_5.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL1999.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2026.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2059.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2097.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2104.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2137.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2159.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2181.5.dat -graph 7 -bxy 1:2 &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0Lam_6.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2208.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2244.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2259.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2305.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2316.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KL2405.dat -graph 5 -bxy 1:2 &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K0Lam_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1633.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1661.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1683.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1694.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1724.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1741.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1758.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1792.dat -graph 7 -bxy 1:2 &  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K0Lam_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1797.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1819.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1825.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1845.5.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1851.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1879.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1909.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1939.dat -graph 7 -bxy 1:2 & 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K0Lam_3.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1966.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL1999.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2028.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2060.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2105.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2159.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2183.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2208.dat -graph 7 -bxy 1:2 & 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K0Lam_4.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2260.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KL2316.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/P_x_dsdo_KzL1626.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/P_x_dsdo_KzL1648.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/P_x_dsdo_KzL1672.dat -graph 6 -bxy 1:2 &
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/spinrot_K0Lam.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL1852.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL1941.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL2030.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL2062.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL2107.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL2160.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KzL2261.dat -graph 6 -bxy 1:2 &
#--------------------------------------------------------------------------------------------------------------------------------
#
#   Plots Differential cross sections and Polarization of pi^-p --> K^0 Sigma^0
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot4
plot4:
	xmgrace plot_minuit/dsdo_K0S0_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1694.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1724.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1741.dat -graph 2 -bxy 1:2  -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1758.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1792.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1797.dat -graph 5 -bxy 1:2  -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1819.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1825.dat -graph 7 -bxy 1:2 & 	 
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0S0_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1845.5.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1879.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1909.dat -graph 2 -bxy 1:2   -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1930.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1934.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1938.dat -graph 5 -bxy 1:2  -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1966.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1978.dat -graph 7 -bxy 1:2 & 	  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0S0_3.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz1999.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2026.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2059.dat -graph 2 -bxy 1:2  -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2097.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2104.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2137.dat -graph 5 -bxy 1:2  -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2181.5.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2208.dat -graph 7 -bxy 1:2 & 	  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K0S0_4.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2244.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2259.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2305.dat -graph 2 -bxy 1:2  -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2316.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KzSz2405.dat -graph 4 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K0S0_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1694.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1724.5.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1758.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1792.5.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1825.5.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1847.5.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1879.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1909.dat -graph 7 -bxy 1:2 & 	  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K0S0_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1938.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1966.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz1999.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2027.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2059.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2104.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2159.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2183.dat -graph 7 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2208.dat -graph 8 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2259.dat -graph 9 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KzSz2316.dat -graph 10 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------#
#   Plots Differential cross sections and Polarization of pi^-p --> K^+ Sigma^-
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot5
plot5:
	xmgrace plot_minuit/dsdo_K+S-_1.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1739.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1763.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1792.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1818.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1843.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1930.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1973.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm1978.dat -graph 7 -bxy 1:2 & 	  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_K+S-_2.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2025.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2097.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2137.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2180.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2244.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2305.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSm2405.dat -graph 6 -bxy 1:2 & 	  
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_K+S-.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSm1743.dat -graph 0 -bxy 1:2 & 	  
#--------------------------------------------------------------------------------------------------------------------------------

#
#   Plots Differential cross sections and Polarization of pi^+p --> K^+Sigma^+
#
#--------------------------------------------------------------------------------------------------------------------------------
.PHONY : plot6
plot6:
	xmgrace plot_minuit/dsdo_k+s+_low.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1729.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1732.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1757.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1764.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1783.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1789.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1790.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1813.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_k+s+.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1822.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1845.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1870.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1891.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1926.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1939.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1970.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp1985.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_k+s+_up.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2019.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2031.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2059.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2074.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2106.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2118.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2147.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2158.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/dsdo_k+s+_high.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2188.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2202.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2224.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2243.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2261.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2282.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2304.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_differential_cs/dsdo_KpSp2318.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_k+s+_low.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1729.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1732.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1757.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1764.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1783.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1789.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1790.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1813.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_k+s+.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1822.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1845.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1870.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1891.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1926.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1939.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1970.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp1985.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_k+s+_up.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2019.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2031.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2059.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2074.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2106.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2118.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2147.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2158.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/pola_k+s+_high.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2188.dat -graph 0 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2202.dat -graph 1 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2224.dat -graph 2 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2243.dat -graph 3 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2261.dat -graph 4 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2282.dat -graph 5 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2304.dat -graph 6 -bxy 1:2 -autoscale none -block plot_minuit/fit_result/KY_polarization/pola_KpSp2318.dat -graph 7 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------
	xmgrace plot_minuit/spinrot_KpSp.agr -settype xy -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KpSp2021.dat -graph 0 -bxy 1:2 -settype xy -autoscale none -block plot_minuit/fit_result/KY_spin-rotation/beta_KpSp2107.dat -graph 1 -bxy 1:2 & 	
#--------------------------------------------------------------------------------------------------------------------------------


